language: node_js
node_js:
  - "6"

sudo: required

before_script:
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - heroku --version

script:
  -  npm test && npm run build

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  skip_cleanup: true

