const ActionTypes = {
  RECEIVE_CURRENT_USER: 'RECEIVE_CURRENT_USER',
  ATTEMPT_LOGIN: 'ATTEMPT_LOGIN',
  LOGOUT: 'LOGOUT',
  LOGGING_IN: 'LOGGING_IN',
  IS_FETCHING_CURRENT_USER: 'IS_FETCHING_CURRENT_USER'
};

export {
  ActionTypes
};
